[package]
name = "terra-block-component"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
terra-device-transport = { path = "../device-transport" }
terra-limits = { path = "../../crates/terra-limits" }
wit-bindgen = { workspace = true, features = ["async-spawn", "inter-task-wakeup"] }
futures = { version = "0.3", default-features = false }
