package terra:mmio@0.1.0;

interface machine-types {
    enum architecture { x86, arm }
    enum device-kind { block, net, vsock, fs, memory }
    record device { kind: device-kind, mmio-base: u64, irq: u32 }
    enum error { invalid-ram, invalid-vcpus, too-many-devices, platform, already-created, invalid-state }
}

interface machine {
    use machine-types.{error};
    use virtualization.{config, vm};
    use platform.{vcpu};

    initialize: func(config: config, vm: own<vm>, vcpus: list<own<vcpu>>) -> result<_, error>;
    compose: func() -> result<_, error>;
}
