[package]
name = "terra-vsock-device"
version = "0.0.1"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/terrarium-sh/terrarium"
rust-version = "1.95"

[features]
fuzzing = []

[dependencies]
terra-protocol = { path = "../../crates/terra-protocol" }

[target.'cfg(unix)'.dev-dependencies]
virtio-vsock = "0.12"

[lints]
workspace = true
