[package]
name = "terra-boot-component"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
vm-fdt = { version = "0.3", default-features = false, features = ["alloc"] }
wit-bindgen.workspace = true
terra-limits = { path = "../../crates/terra-limits" }
