[package]
name = "terra-shared"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
rustix = { version = "1", default-features = false, features = ["fs", "std"] }

[lints]
workspace = true
