[package]
name = "terra-platform"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
terra-limits = { path = "../terra-limits" }

[target.'cfg(unix)'.dependencies]
libc.workspace = true
tokio = { version = "1", features = ["net", "io-util"] }
rustix.workspace = true
vm-memory = { version = "0.18", features = ["backend-mmap"] }

[target.'cfg(target_os = "linux")'.dependencies]
kvm-bindings = "0.14"
kvm-ioctls = "0.25"

[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'.dependencies]
applevisor = { version = "=1.0.0", default-features = false, features = ["macos-15-0"] }
applevisor-sys = { version = "=1.0.0", default-features = false, features = ["macos-15-0"] }

[target.'cfg(target_os = "windows")'.dependencies]
uds_windows = "1.2.1"
tokio = { version = "1", features = ["io-util", "rt"] }
async-io = "2.6.0"
tokio-util = { version = "0.7", features = ["compat"] }
log = "0.4.34"
windows-sys = { version = "0.61", features = ["Wdk_Foundation", "Win32_Security", "Wdk_Storage_FileSystem", "Wdk_System_SystemServices", "Win32_Storage_FileSystem", "Win32_System_IO", "Win32_System_Ioctl", "Win32_System_Memory", "Win32_System_SystemInformation", "Win32_System_Hypervisor"] }

[dev-dependencies]
tempfile.workspace = true
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "sync", "time"] }

[lints]
workspace = true
