[package]
name = "terra-vsock-component"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
terra-protocol = { path = "../../crates/terra-protocol", features = ["mux"] }
terra-device-transport = { path = "../device-transport" }
terra-limits = { path = "../../crates/terra-limits" }
terra-vsock-device = { path = "../vsock-device" }
wit-bindgen = { workspace = true, features = ["async-spawn", "inter-task-wakeup"] }
futures-util = { version = "0.3", default-features = false, features = ["std", "io"] }
futures-channel = "0.3"
futures-io = "0.3"
yamux = "=0.14.1"
serde = "1"
