[package]
name = "terra-vsock-frontend-component"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
fuzzing = []

[dependencies]
terra-device-transport = { path = "../device-transport" }
terra-vsock-device = { path = "../vsock-device" }
terra-limits = { path = "../../crates/terra-limits" }
wit-bindgen = { workspace = true, features = ["async-spawn", "inter-task-wakeup"] }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
terra-protocol = { path = "../../crates/terra-protocol" }
terra-policy = { path = "../../crates/terra-policy" }
