[package]
name = "terra-fs-component"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
terra-device-transport = { path = "../device-transport" }
terra-limits = { path = "../../crates/terra-limits" }
wit-bindgen = { workspace = true, features = ["async-spawn", "inter-task-wakeup", "futures-stream"] }
futures = "0.3"
